services:
  optuna-postgres:
    image: postgres:17.2-alpine3.21
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - ${HOME}/dev-postgres/optuna/:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - chem-network
    restart: always
  benchmark-postgres:
    build:
      context: docker
      dockerfile: BenchmarkDB.Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - ${HOME}/dev-postgres/chem:/var/lib/postgresql/data
    ports:
      - 5431:5432
    networks:
      - chem-network
    shm_size: 60g # must be greater than the size of the database
    restart: always
  rapids-notebooks:
    image: nvcr.io/nvidia/rapidsai/notebooks:24.08-cuda12.2-py3.11
    volumes:
      - ./:/home/rapids/notebooks/chem-mrl
    environment:
      CUDA_VISIBLE_DEVICES: "0"
    # user: "1001:1001" # standard for ubuntu
    ports:
      - 8888:8888
      - 8787:8787
      - 8786:8786
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    shm_size: 1g
    ulimits:
      memlock: -1
      stack: 67108864
    networks:
      - chem-network
networks:
  chem-network:
